### PR TITLE
Add profile links after battle ends

### PR DESCRIPTION
**Pull request by abhijeet-26**
## Fixes Issue
#18 

## Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

image

### CODE REVIEW

**Review by Ananya2001-an — APPROVED** [review]
Looks good. Thanks for your contribution 😊

**Comment by abhijeet-26** [comment]
I want to improve UI. Can I work on it?

**Comment by Ananya2001-an** [comment]
Yes sure but I will have to raise a separate issue for that. We have to divide the work in chunks to make it simpler. Hope you understand.

**Comment by abhijeet-26** [comment]
Yeah definately.

**Comment by abhijeet-26** [comment]
I think the fonts you used are not eye-catching. Take it as a suggestion.

**Comment by Ananya2001-an** [comment]
> I think the fonts you used are not eye-catching. Take it as a suggestion.

Sure we have to work on the UI @abhijeet-26 but since that's a big task it will take time for implementations. We have to discuss some designs and then do the refactoring accordingly. Moreover we have some other issues with the api itself which are more important to solve rather than just focusing on the UI right now.

**Comment by abhijeet-26** [comment]
Create issue for API. I will do it.

**Comment by Ananya2001-an** [comment]
> Create issue for API. I will do it.

Actually someone is already working on it and he has a draft PR raised for the same.

**Pull request merged**
