### PR TITLE
Made changes in Confetti state

### LINKED ISSUE #19: [BUG]: stop confetti animation after some time
**Describe the bug**
The confetti animation at the end should stop after few mins. Maybe after 1 min.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by Kd-Here**
Use 5sec timer

## Fixes Issue
closes #19 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Note to reviewers

Resolved the issue explained in #17

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @Kd-Here can you make the stop transition smooth. It stops very abruptly right now. Once that's done we can merge it.

**Comment by Kd-Here** [comment]
> Hey @Kd-Here can you make the stop transition smooth. It stops very abruptly right now. Once that's done we can merge it.

Sure I will try to implement that.

**Comment by Kd-Here** [comment]
@Ananya2001-an as I am new to React and Js found difficult to edit the state usign api.
I love to take challenges but today wasted couple of hrs just figuring it, and don't want to try more sorry.

**Comment by Ananya2001-an** [comment]
> @Ananya2001-an as I am new to React and Js found difficult to edit the state usign api.
> I love to take challenges but today wasted couple of hrs just figuring it, and don't want to try more sorry.

Sure no issues I will merge your work in a temporary branch tomorrow and then work on it on my own. Thanks for your efforts @Kd-Here

**Pull request merged**
